# -*- coding: utf-8 -*-
"""고객정보_csv_파일생성.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HI6JZmKSxL2mYbmmHwFg5Ol2jy-RXBfU

##이름생성
"""



import itertools
import random
import collections

#csv파일 생성
#김민준,kimmj,21,강남점,'010-1111-1111'
#지점 = ['강남','서초','판교','도봉']
#이름, id, 나이, 주로 가는 지점, 전화번호

#이름 생성
def nameSplit():
    name1 = ["김","이","박","최","정"]
    first_name = ["민준","지후","지훈","준서","현우","예준"]
    name2 = []
    name3 = []

    for name in first_name:
        name2.append(name[0])
        name3.append(name[1])

    #중복제거
    name2 = list(set(name2))
    name3 = list(set(name3))

    return name1,name2,name3


#itertools.product 로 이름 생성하는 함수
def generateName(name1,name2,name3):
    producted_name = list(itertools.product(name1,name2,name3))
    #문자열로 변경 + name2와 3이 중복된것은 제외
    names = [''.join(name) for name in producted_name if name[1] != name[2]]
    random.shuffle(names)     #섞어서 출력하고 싶을때
    return names    #정해진 갯수만큼만 출력하기


def getName1():
    name1,name2,name3 = nameSplit()
    return generateName(name1,name2,name3)[0]


getName1()

"""##아이디생성"""

#아이디생성

#문자열 5개를 랜덤으로 추출한다.
import random

def get_id():
    customer_id = []
    string = "abcdefghijklmnopqrstuvwxyz"


        #자릿수도 매번 달라지도록 for문에 넣었음
    digit = random.randint(4,10)
    random_num = random.randint(0,2000)
    random_id = random.sample(string,digit)
    result = ''.join(random_id) + str(random_num)
    customer_id.append(result)

    return customer_id
    # print(len(customer_id))

get_id()

"""##선호하는 지점"""

#선호하는 지점 선택

def get_cafe():
    favorite_cafe = []
    cafe_sesac = ['강남','서초','금천','양재','송파','인천','잠실','도봉','왕십리','동대문','부산','대구','안산','홍대']

    cafe = random.choice(cafe_sesac)
    favorite_cafe.append(cafe)

    return favorite_cafe

get_cafe()

"""##나이"""

#나이
#가중치 필요
#15세~75세

def get_age():
    customer_age = []

    age_group = [(10,19),(20,29),(30,39),(40,49),(50,59),(60,69),(70,79)]
    weight = [0.05,0.2,0.3,0.23,0.1,0.07,0.05]

    generation = random.choices(age_group,weights = weight)[0]
    # print(generation)
    age2 = random.randint(generation[0],generation[1])
    customer_age.append(age2)
    return customer_age
    # print(len(customer_age))

    #가중치 적용 확인코드
    count=[]
    for i in range(7):
        count.append(0)

    for age in customer_age:
        if age >= 10 and age <= 19:
            count[0]+=1
        elif age >= 20 and age <= 29:
            count[1]+=1
        elif age >= 30 and age <= 39:
            count[2]+=1
        elif age >= 40 and age <= 49:
            count[3]+=1
        elif age >= 50 and age <= 59:
            count[4]+=1
        elif age >= 60 and age <= 69:
            count[5]+=1
        else:
            count[6]+=1

    # print(count)

get_age()

"""##전화번호생성"""

#전화번호생성

# 010-1234-5567

def get_phone_number():

    numbers = '1234567890'
    customer_number = ""

    num1 = ''.join(random.sample(numbers,4))
    num2 = ''.join(random.sample(numbers,4))

    phone_number = f'010-{num1}-{num2}'
    customer_number=phone_number

    return customer_number

get_phone_number()

"""##데이터프레임 및 csv파일 생성"""

import pandas as pd
import os

user_infos = []

for k in range(100):
    name = getName1()
    member_ID = get_id()
    cafe = get_cafe()
    age = get_age()
    phone_number = get_phone_number()

    user_infos.append([name, member_ID, cafe, age, phone_number])

columns_name = ['이름', '회원ID', '선호지점','나이','휴대폰번호']
df = pd.DataFrame(user_infos, columns = columns_name)
df.index = df.index+1
print(df)

print(os.getcwd())
df.to_csv("user.csv")

"""##생성된 파일 삭제"""

os.remove("user.csv")
