# -*- coding: utf-8 -*-
"""이름생성.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CdWf1bxL51rcpf7m2nBXrIS83eoOu6c
"""

# def prepareName():
#     name1 = ["김","이","박","최","정"]
#     first_name = ["민준","지후","지훈","준서","현우","예준"]
#     name2 = []
#     name3 = []

#     for name in first_name:
#         name2.append(name[0])
#         name3.append(name[1])

#         #중복제거
#     name2 = list(set(name2))
#     name3 = list(set(name3))

#     name = [name1,name2,name3]

#     return name

# def generateName2(n,name):
#     generated_name2 = []

#     # for name in range(100):
#     while len(set(generated_name2)) < n:
#         temp1 = random.choice(name[1])
#         temp2 = random.choice(name[2])
#         if temp1 != temp2:

#             generated_name2.append(random.choice(name[0])+temp1+temp2)
#         # random.shuffle(generated_name2)
#     # return print(getName[:n])
#     return list(set(generated_name2))

# name = prepareName()
# genName = generateName2(100, name)
# print(genName)
# print(len(genName))

#함수로 정의할 때 생각해볼점

#0. 함수를 어떻게 쪼갤것인가
#1. 함수명
#2. 인수값+리턴값(입력+출력)

# def generateName
# def nameSplit

import itertools
import random
import collections

#csv파일 생성
#김민준,kimmj,21,강남점,'010-1111-1111'
#지점 = ['강남','서초','판교','도봉']
#이름, id, 나이, 주로 가는 지점, 전화번호


def nameSplit():
    name1 = ["김","이","박","최","정"]
    first_name = ["민준","지후","지훈","준서","현우","예준"]
    name2 = []
    name3 = []

    for name in first_name:
        name2.append(name[0])
        name3.append(name[1])

    #중복제거
    name2 = list(set(name2))
    name3 = list(set(name3))

    return name1,name2,name3





# name1 = ["김","이","박","최","정"]
# first_name = ["민준","지후","지훈","준서","현우","예준"]
# name2 = []
# name3 = []

# for name in first_name:
#     name2.append(name[0])
#     name3.append(name[1])

#     #중복제거
# name2 = list(set(name2))
# name3 = list(set(name3))




#itertools.product 로 이름 생성하는 함수
def generateName(n,name1,name2,name3):
    producted_name = list(itertools.product(name1,name2,name3))
    #문자열로 변경 + name2와 3이 중복된것은 제외
    names = [''.join(name) for name in producted_name if name[1] != name[2]]
    random.shuffle(names)     #섞어서 출력하고 싶을때
    return names[:n]      #정해진 갯수만큼만 출력하기


#random.choice로 이름 생성하는 함수
def generateName2(n,name1,name2,name3):
    generated_name2 = []

    # for name in range(100):
    while len(set(generated_name2)) < n:
        temp1 = random.choice(name2)
        temp2 = random.choice(name3)
        if temp1 != temp2:
            generated_name2.append(random.choice(name1)+temp1+temp2)
    return list(set(generated_name2))


#random.choice + while문으로 중복제거하는 함수
def generateName3(n,name1,name2,name3):
    generated_name3 = []

    for name in range(n):
        temp1 = random.choice(name2)
        temp2 = random.choice(name3)

        while temp1 == temp2:
            temp2 = random.choice(name3)
        generated_name3.append(random.choice(name1)+temp1+temp2)

    generated_name3 = list(set(generated_name3))
    random.shuffle(generated_name3)
    return generated_name3[:n]



def getName1():
    n = int(input("몇 개의 이름을 생성할까요?"))
    name1,name2,name3 = nameSplit()
    print(generateName(n,name1,name2,name3))


def getName2():
    name1,name2,name3 = nameSplit()
    genName = generateName2(name1,name2,name3)
    print(generateName2(n,name1,name2,name3))
    print(len(genName))


def getName3():
    n = int(input("몇 개의 이름을 생성할까요?"))
    name1,name2,name3 = nameSplit()
    print(generateName3(n,name1,name2,name3))

import itertools
import random
import collections

#csv파일 생성
#김민준,kimmj,21,강남점,'010-1111-1111'
#지점 = ['강남','서초','판교','도봉']
#이름, id, 나이, 주로 가는 지점, 전화번호


def nameSplit():
    name1 = ["김","이","박","최","정"]
    first_name = ["민준","지후","지훈","준서","현우","예준"]
    name2 = []
    name3 = []

    for name in first_name:
        name2.append(name[0])
        name3.append(name[1])

    #중복제거
    name2 = list(set(name2))
    name3 = list(set(name3))

    return name1,name2,name3

#random.choice로 이름 생성하는 함수
def generateName2(name1,name2,name3):
    generated_name2 = []
    # while len(set(generated_name2)) < 100:
    temp1 = random.choice(name2)
    temp2 = random.choice(name3)
    if temp1 != temp2:
        generated_name2.append(random.choice(name1)+temp1+temp2)
    return list(set(generated_name2))


def getName2():
    name1,name2,name3 = nameSplit()
    genName = generateName2(name1,name2,name3)
    # print(generateName2(name1,name2,name3))
    # print(len(genName))
    return genName

getName2()

import itertools
import random
import collections

#csv파일 생성
#김민준,kimmj,21,강남점,'010-1111-1111'
#지점 = ['강남','서초','판교','도봉']
#이름, id, 나이, 주로 가는 지점, 전화번호


def nameSplit():
    name1 = ["김","이","박","최","정"]
    first_name = ["민준","지후","지훈","준서","현우","예준"]
    name2 = []
    name3 = []

    for name in first_name:
        name2.append(name[0])
        name3.append(name[1])

    #중복제거
    name2 = list(set(name2))
    name3 = list(set(name3))

    return name1,name2,name3


#itertools.product 로 이름 생성하는 함수
def generateName(name1,name2,name3):
    producted_name = list(itertools.product(name1,name2,name3))
    #문자열로 변경 + name2와 3이 중복된것은 제외
    names = [''.join(name) for name in producted_name if name[1] != name[2]]
    random.shuffle(names)     #섞어서 출력하고 싶을때
    return names    #정해진 갯수만큼만 출력하기


def getName1():
    name1,name2,name3 = nameSplit()
    return generateName(name1,name2,name3)[0]


getName1()

#itertools.product
getName1()

#random.choice
getName2()

#random.choice + while
getName3()