# -*- coding: utf-8 -*-
"""파일만들기/이름바꾸기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlx_JSr9W88zJsNjXdB20eS3n_XStnJ1


import os
import string
import random
from pathlib import Path


#[과제1] 비어있는 파일 30개를 생성하고, 파일명은 랜덤으로 네임을 준다.확장자는 txt
# 현재 폴더의 txt 파일의 갯수를 출력하고
# 파일명이 a로 시작되는 경우 파일 리스트를 별도로 저장하고
# 파일을 삭제한다.

#[과제2]
#(선행조건) 과제1을 수행하고 생성된 파일이 있는 상태에서 과제 2를 수행
#txt 파일 이름을 myText[숫자].txt로 변경해준다.


#파일을 담아서 출력하기위한 빈 리스트 생성
filenames = []

#랜덤 문자열 추출을 위한 재료
string = 'abcdefghijklmnopqrstuvwxyz'

#파일명 길이 설정
letter_length = 6



# 파일 생성 
#https://codechacha.com/ko/python-touch-file/

#1. path 라이브러리 사용 
# pathlib.Path.touch는 Path의 경로에 대한 빈파일을 생성합니다. (참고로, touch는 쉘 명령어에서 빈 파일을 생성하는 명령어입니다.)

#2. open 
# open()으로 파일을 write 모드로 열고, 아무것도 입력하지 않고 파일을 닫으면 빈 파일이 생성됩니다.

#3. os.system
# os.system()는 인자로 전달된 쉘 명령어를 실행합니다. 빈 파일을 생성하는 touch 명령어를 사용하여 현재 working directory 아래에 빈 파일을 생성할 수 있습니다.


#30개의 파일을 생성 - 파일명은 랜덤으로 추출
for i in range(1,31):
    random_letter = random.sample(string,letter_length)
    result = ''.join(random_letter)+'.txt'
    filenames.append(result)
    # 파일생성1
    Path(result).touch()
    # 파일생성2
    # file_path = Path(fileName)
    # file_path.touch()

#30개의 파일
print(f'랜덤파일명으로 생성된 30개의 파일 : {filenames}')


#a로 시작하는 파일을 따로 담을 리스트
file_with_a = []

#a로 시작하는 파일은 별도의 리스트에 담고 삭제한다.
for filename in filenames:
    if filename[0] == 'a':
    #if filename.startwith('a'):
        file_with_a.append(filename)
        os.remove(filename)
        filenames.remove(filename)
print(f'a로 시작하는 파일 : {file_with_a}')
print(f'a로 시작하는 파일을 삭제 한 후 : {filenames}')
print(f'a로 시작하는 파일을 삭제 한 후 파일 수 : {len(filenames)}')


#파일명 변경은 아래 코드셀에서 처리함
# for num, filename in enumerate(filenames):
#     changeName = "myText" + str(num+1) + ".txt"
#     os.rename(filename,changeName)

# #myText로 파일명을 변경한 뒤 파일명을 출력
cur_list = os.listdir()
print(f'기본파일을 포함한 파일 수 : {len(cur_list)}')

"""##파일명 변경"""

for num, filename in enumerate(filenames):
    changeName = "myText" + str(num+1) + ".txt"
    os.rename(filename,changeName)
    print(changeName)

"""##txt파일만 추출"""

current_list = os.listdir()

txt_files = []
for txt_file in current_list:
    if os.path.splitext(txt_file)[1] == '.txt':
        txt_files.append(txt_file)

print(f'txt파일들 : {txt_files}')
print(f'txt파일 수 : {len(txt_files)}')
